language: python
sudo: false
language: python
matrix:
  - python: '2.7'
  - python: '3.5'
  - python: '3.6'
  - python: '3.7'
    dist: xenial
env:
  - CONFIG=buildout.cfg
install:
  - pip install -U pip setuptools zc.buildout
  - buildout parts=test -c $CONFIG
before_script:
  - export TZ=US/Eastern
script: bin/test -vvv
cache:
  directories:
    - $HOME/.cache/pip
    - eggs
before_cache:
    - rm -f $HOME/.cache/pip/log/debug.log
